version: '3'
networks:
  web:
    external: true
  internal:
    external: false
services:
  registrocovid-front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    labels:
      - traefik.frontend.rule=Host:registrocovid.local
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
    networks:
      - internal
      - web


